/*
 * gpio-sensor.c — simulated GPIO sensor character device
 *
 * Registers /dev/gpio-sensor.  Each read() returns one 10-bit ADC sample
 * (0-1023) as a decimal string, generated by a software LCG so the value
 * changes on every call without needing real hardware.
 */

#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/fs.h>       /* file_operations, alloc_chrdev_region */
#include <linux/cdev.h>     /* cdev_init, cdev_add */
#include <linux/device.h>   /* class_create, device_create */
#include <linux/uaccess.h>  /* copy_to_user */

#define DEVICE_NAME "gpio-sensor"
#define CLASS_NAME  "gpio_sensor"
#define BUF_SIZE    32

static dev_t   dev_num;       /* kernel-assigned major:minor */
static struct cdev   gpio_cdev;
static struct class *gpio_class;
static struct device *gpio_dev;

/* Simulated sensor state -------------------------------------------------- */

static u32 sensor_seed    = 0x12345678;
static u32 sensor_counter = 0;

/*
 * Linear Congruential Generator — the same multiplier/increment used by
 * many C stdlib rand() implementations (Numerical Recipes constants).
 * Produces a full 32-bit period; we discard the low bits and mask to 10
 * bits to mimic a 10-bit ADC reading in [0, 1023].
 */
static u32 next_reading(void)
{
	sensor_seed = sensor_seed * 1664525u + 1013904223u;
	return (sensor_seed >> 22) & 0x3FF;
}

/* file_operations callbacks ----------------------------------------------- */

static int gpio_open(struct inode *inode, struct file *file)
{
	pr_info(DEVICE_NAME ": open\n");
	return 0;
}

static int gpio_release(struct inode *inode, struct file *file)
{
	pr_info(DEVICE_NAME ": release\n");
	return 0;
}

/*
 * Each read() call returns one fresh sample followed by a newline.
 * We set *ppos after the first call so a second read() within the same
 * open() sees EOF — this matches the behaviour tools like `cat` expect
 * from a sensor device.
 */
static ssize_t gpio_read(struct file *file, char __user *buf,
			 size_t count, loff_t *ppos)
{
	char tmp[BUF_SIZE];
	int  len;
	u32  val;

	if (*ppos > 0)          /* already returned one sample this open */
		return 0;

	val = next_reading();
	sensor_counter++;

	len = snprintf(tmp, sizeof(tmp), "%u\n", val);

	if (count < (size_t)len)
		return -EINVAL;

	if (copy_to_user(buf, tmp, len))
		return -EFAULT;

	*ppos = len;
	return len;
}

static ssize_t gpio_write(struct file *file, const char __user *buf,
			  size_t count, loff_t *ppos)
{
	/* Writes are accepted but ignored for now (ioctl will handle control) */
	pr_info(DEVICE_NAME ": write (%zu bytes ignored)\n", count);
	return count;
}

static const struct file_operations gpio_fops = {
	.owner   = THIS_MODULE,
	.open    = gpio_open,
	.release = gpio_release,
	.read    = gpio_read,
	.write   = gpio_write,
};

/* Module init / exit ------------------------------------------------------- */

static int __init gpio_sensor_init(void)
{
	int ret;

	/*
	 * alloc_chrdev_region() asks the kernel to pick an unused major number
	 * and assign it to us.  Minor base = 0, count = 1 device.
	 */
	ret = alloc_chrdev_region(&dev_num, 0, 1, DEVICE_NAME);
	if (ret < 0) {
		pr_err(DEVICE_NAME ": alloc_chrdev_region failed (%d)\n", ret);
		return ret;
	}

	/* Wire the fops table to the cdev object and register it */
	cdev_init(&gpio_cdev, &gpio_fops);
	gpio_cdev.owner = THIS_MODULE;

	ret = cdev_add(&gpio_cdev, dev_num, 1);
	if (ret < 0) {
		pr_err(DEVICE_NAME ": cdev_add failed (%d)\n", ret);
		goto err_cdev;
	}

	/*
	 * class_create() adds an entry under /sys/class/gpio_sensor.
	 * udev (or mdev in busybox) watches sysfs and responds to the
	 * uevent we emit in device_create() by making /dev/gpio-sensor.
	 */
	gpio_class = class_create(CLASS_NAME);
	if (IS_ERR(gpio_class)) {
		ret = PTR_ERR(gpio_class);
		pr_err(DEVICE_NAME ": class_create failed (%d)\n", ret);
		goto err_class;
	}

	gpio_dev = device_create(gpio_class, NULL, dev_num, NULL, DEVICE_NAME);
	if (IS_ERR(gpio_dev)) {
		ret = PTR_ERR(gpio_dev);
		pr_err(DEVICE_NAME ": device_create failed (%d)\n", ret);
		goto err_device;
	}

	pr_info(DEVICE_NAME ": loaded  major=%d minor=%d\n",
		MAJOR(dev_num), MINOR(dev_num));
	return 0;

err_device:
	class_destroy(gpio_class);
err_class:
	cdev_del(&gpio_cdev);
err_cdev:
	unregister_chrdev_region(dev_num, 1);
	return ret;
}

static void __exit gpio_sensor_exit(void)
{
	device_destroy(gpio_class, dev_num);
	class_destroy(gpio_class);
	cdev_del(&gpio_cdev);
	unregister_chrdev_region(dev_num, 1);
	pr_info(DEVICE_NAME ": unloaded\n");
}

module_init(gpio_sensor_init);
module_exit(gpio_sensor_exit);

MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("Simulated GPIO sensor character device");
MODULE_AUTHOR("Custom Yocto Layer");
